version: '3'
services:
  project:
    build: .
    ports:
      - "4000:80"
    networks:
      - movie-net
    volumes:
      - .:/app
    command: python movies.py
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - movie-net

  spark-master:
    image: bitnami/spark:3.5.1
    command: bash -c "pip install pymongo requests && bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      PYTHONPATH: '/opt/bitnami/spark'
    volumes:
      - ./src:/opt/bitnami/spark/src
    networks:
      - movie-net
  spark-worker-1:
    image: bitnami/spark:3.5.1
    command: bash -c "pip install pymongo requests && bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment: 
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2 
      SPARK_WORKER_MEMORY: 1G
      PYTHONPATH: '/opt/bitnami/spark'
    volumes:
      - ./src:/opt/bitnami/spark/src
    depends_on: 
      - spark-master
    networks:
      - movie-net
  spark-worker-2:
    image: bitnami/spark:3.5.1
    command: bash -c "pip install pymongo requests && bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment: 
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2 
      SPARK_WORKER_MEMORY: 1G
      PYTHONPATH: '/opt/bitnami/spark'
    volumes:
      - ./src:/opt/bitnami/spark/src
    depends_on: 
      - spark-master
    networks:
      - movie-net

networks:
  movie-net:
